# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  	desc "A lane for execute unit tests and extract the code coverage"
  	lane :test do
      clear_derived_data

    	scan
    	
    	xcov(
          project: "GitHubAPI.xcodeproj",
          scheme: "GitHubAPI",
          output_directory: "fastlane/test_output",
          minimum_coverage_percentage: 80.0,
          skip_slack: true
      )

    	swiftlint(
      		mode: :lint,  
      		output_file: "swiftlint.html", 
      		config_file: ".swiftlint.yml",    
      		reporter: 'html',
      		ignore_exit_status: true 
    	)
    	lintreport(filename: "swiftlint.html")
  	end
end
